spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all endpoints in the gateway
            allowedOrigins: "http://localhost:4200"  # Allow frontend origin (Angular)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"  # Allow all headers
            allowCredentials: true  # If needed


      routes:
        - id : r1
          uri : http://localhost:8081/
          predicates :
            - Path= /customers/**
        - id : r2
          uri : http://localhost:8082/
          predicates :
            - Path= /products/**



    discovery:
      enabled: true
server:
  port: 888


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/